recipe: default.v1
language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 10
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 10
  retrieval_intent: ask_question

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 3
  epochs: 10
- name: TEDPolicy
  max_history: 3
  epochs: 10
assistant_id: 20250919-111213-inscribed-ghoul
